-- Create admin users table
CREATE TABLE admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;

-- Create policy
CREATE POLICY "Enable all access for admin_users" ON admin_users
    FOR ALL TO PUBLIC
    USING (true)
    WITH CHECK (true);

-- Grant permissions
GRANT ALL ON admin_users TO anon;
GRANT USAGE ON SEQUENCE admin_users_id_seq TO anon;
