-- Create admin users table if it doesn't exist
CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert admin user with hashed password for 'Admin@123'
INSERT INTO admin_users (username, password_hash)
VALUES (
    'admin',
    '$2b$10$8X0GkFgB5B5Jp0P1Xl3YUu.gQgQIxqPF6WTD0BJKyZh1oL8lFPCiO'
);

-- Enable RLS
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;

-- Create policy
CREATE POLICY "Enable all access for admin_users" ON admin_users
    FOR ALL TO PUBLIC
    USING (true)
    WITH CHECK (true);

-- Grant permissions
GRANT ALL ON admin_users TO anon;
GRANT USAGE ON SEQUENCE admin_users_id_seq TO anon;
