-- Reset everything first
DROP TABLE IF EXISTS reference_details;
DROP TABLE IF EXISTS academic_details;
DROP TABLE IF EXISTS form_data;

-- Create main form table
CREATE TABLE form_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    mobile_number VARCHAR(15) NOT NULL,
    address TEXT NOT NULL,
    dob DATE NOT NULL,
    joining_date DATE NOT NULL,
    aadhar_number VARCHAR(12) NOT NULL,
    father_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create academic details table
CREATE TABLE academic_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id BIGINT REFERENCES form_data(id) ON DELETE CASCADE,
    qualification VARCHAR(100) NOT NULL,
    college VARCHAR(100) NOT NULL,
    passing_year INTEGER NOT NULL,
    percentage DECIMAL(5, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create reference details table
CREATE TABLE reference_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id BIGINT REFERENCES form_data(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    mobile_number VARCHAR(15) NOT NULL,
    relation VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Set up permissions
ALTER TABLE form_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE academic_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE reference_details ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Enable all access for form_data" ON form_data FOR ALL TO PUBLIC USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for academic_details" ON academic_details FOR ALL TO PUBLIC USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for reference_details" ON reference_details FOR ALL TO PUBLIC USING (true) WITH CHECK (true);

-- Grant permissions
GRANT ALL ON form_data TO anon;
GRANT ALL ON academic_details TO anon;
GRANT ALL ON reference_details TO anon;
GRANT USAGE ON SCHEMA public TO anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon;
