-- Create admin table
CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Function to create or update admin user
CREATE OR REPLACE FUNCTION upsert_admin_user(
    p_username VARCHAR,
    p_password VARCHAR
) RETURNS VOID AS $$
BEGIN
    -- Delete existing admin user if exists
    DELETE FROM admin_users WHERE username = p_username;
    
    -- Insert new admin user with hashed password
    INSERT INTO admin_users (username, password_hash)
    VALUES (
        p_username,
        crypt(p_password, gen_salt('bf'))  -- Using bcrypt for password hashing
    );
END;
$$ LANGUAGE plpgsql;

-- Create extension if not exists
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Insert admin user with credentials
SELECT upsert_admin_user('admin', 'Admin@123');
