-- Drop existing admin_users table
DROP TABLE IF EXISTS admin_users CASCADE;

-- Create extension for password hashing
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Create admin_users table with proper indexes
CREATE TABLE admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index on username for faster lookups
CREATE INDEX idx_admin_users_username ON admin_users(username);

-- Insert default admin user with properly hashed password
INSERT INTO admin_users (username, password_hash)
VALUES (
    'admin',
    crypt('Admin@123', gen_salt('bf', 10))
);

-- Test the password verification
SELECT id, username 
FROM admin_users 
WHERE username = 'admin' 
AND password_hash = crypt('Admin@123', password_hash);
