-- Drop existing tables if they exist
DROP TABLE IF EXISTS reference_details;
DROP TABLE IF EXISTS academic_details;
DROP TABLE IF EXISTS form_data;

-- Recreate form_data table
CREATE TABLE form_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    mobile_number VARCHAR(15) NOT NULL,
    email VARCHAR(100),
    address TEXT NOT NULL,
    dob DATE NOT NULL,
    joining_date DATE NOT NULL,
    aadhar_number VARCHAR(12) NOT NULL,
    pan_number VARCHAR(10),
    father_name VARCHAR(100) NOT NULL,
    height DECIMAL(5, 2),
    weight DECIMAL(5, 2),
    passport_photo_url TEXT,
    aadhar_card_url TEXT,
    bank_details_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Recreate academic_details table
CREATE TABLE academic_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id BIGINT REFERENCES form_data(id) ON DELETE CASCADE,
    qualification VARCHAR(100) NOT NULL,
    institute VARCHAR(100) NOT NULL,
    passing_year INTEGER NOT NULL,
    percentage DECIMAL(5, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Recreate reference_details table
CREATE TABLE reference_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id BIGINT REFERENCES form_data(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    contact VARCHAR(15) NOT NULL,
    relation VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Recreate the stored procedure
CREATE OR REPLACE FUNCTION insert_form_data(
    full_name VARCHAR,
    mobile_number VARCHAR,
    email VARCHAR,
    address TEXT,
    dob DATE,
    joining_date DATE,
    aadhar_number VARCHAR,
    pan_number VARCHAR,
    father_name VARCHAR,
    height DECIMAL,
    weight DECIMAL,
    passport_photo_url TEXT,
    aadhar_card_url TEXT,
    bank_details_url TEXT
) RETURNS BIGINT AS $$
DECLARE
    inserted_id BIGINT;
BEGIN
    INSERT INTO form_data (
        full_name,
        mobile_number,
        email,
        address,
        dob,
        joining_date,
        aadhar_number,
        pan_number,
        father_name,
        height,
        weight,
        passport_photo_url,
        aadhar_card_url,
        bank_details_url
    ) VALUES (
        insert_form_data.full_name,
        insert_form_data.mobile_number,
        insert_form_data.email,
        insert_form_data.address,
        insert_form_data.dob,
        insert_form_data.joining_date,
        insert_form_data.aadhar_number,
        insert_form_data.pan_number,
        insert_form_data.father_name,
        insert_form_data.height,
        insert_form_data.weight,
        insert_form_data.passport_photo_url,
        insert_form_data.aadhar_card_url,
        insert_form_data.bank_details_url
    ) RETURNING id INTO inserted_id;
    
    RETURN inserted_id;
END;
$$ LANGUAGE plpgsql;
