-- Drop existing admin_users table
DROP TABLE IF EXISTS admin_users CASCADE;

-- Create admin_users table with minimal fields
CREATE TABLE admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index on username
CREATE INDEX idx_admin_users_username ON admin_users(username);

-- Insert default admin user with plain password
INSERT INTO admin_users (username, password)
VALUES ('admin', 'Admin@123');
