-- Drop existing admin_users table and recreate
DROP TABLE IF EXISTS admin_users;

CREATE TABLE admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create a simpler admin user with direct password hash
INSERT INTO admin_users (username, password_hash) 
VALUES (
    'admin',
    crypt('Admin@123', gen_salt('bf'))
);
